const products = [
  ['chocolate-cake','cakes','Bolo de chocolate','Massa de chocolate, cobertura cremosa e granulado. Serve até 8 fatias.',45,'🍫'],['carrot-cake','cakes','Bolo de cenoura','Massa de cenoura com cobertura de chocolate. Serve até 8 fatias.',42,'🥕'],['corn-cake','cakes','Bolo de milho cremoso','Bolo de milho com textura cremosa. Serve até 8 fatias.',38,'🌽'],['orange-cake','cakes','Bolo de laranja','Massa leve de laranja com calda cítrica. Serve até 8 fatias.',40,'🍊'],
  ['chocolate-party-cake','celebration-cakes','Bolo festa de chocolate','Bolo decorado com brigadeiro e chocolate. Serve até 15 fatias.',110,'🎂'],['strawberry-party-cake','celebration-cakes','Bolo festa de morango','Bolo decorado com creme e morangos. Serve até 15 fatias.',125,'🍓'],['unicorn-party-cake','celebration-cakes','Bolo temático unicórnio','Bolo decorado para aniversário infantil. Serve até 20 fatias.',160,'🦄'],['wedding-mini-cake','celebration-cakes','Mini bolo de casamento','Bolo branco decorado com flores comestíveis. Serve até 12 fatias.',140,'💍'],
  ['brigadeiro-box','sweets','Caixa de brigadeiros','Caixa com 12 brigadeiros tradicionais.',30,'🍬'],['gourmet-sweets-box','sweets','Caixa de doces gourmet','Caixa com 12 doces nos sabores leite ninho, pistache e chocolate.',42,'🍡'],['afternoon-kit','sweets','Kit café da tarde','Bolo de milho, 6 brigadeiros e 6 beijinhos.',58,'☕'],['gift-kit','sweets','Kit presente','Mini bolo de chocolate e caixa com 6 brigadeiros.',52,'🎁']
].map(([id,category,name,description,price,icon])=>({id,category,name,description,price,icon,available:true,hidden:false}));
const state = { cart:[{id:'chocolate-cake',quantity:1},{id:'brigadeiro-box',quantity:1}], selectedProduct:'chocolate-cake', category:'all', delivery:'delivery', payment:'Pix', adminStatus:'received', adminMode:'delivery', rating:0, products };
const app = document.querySelector('#app');
const money = value => value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const product = id => state.products.find(item=>item.id===id);
const cartItems = () => state.cart.map(item=>({...product(item.id),quantity:item.quantity}));
const subtotal = () => cartItems().reduce((sum,item)=>sum+item.price*item.quantity,0);
const fee = () => state.delivery==='delivery'?8:0;
const go = screen => { location.hash=screen; };
const button = (text,action,kind='primary') => `<button class="${kind}" onclick="${action}">${text}</button>`;
function screenHeader(title,back='catalog') { return `<header class="topbar">${back?`<button class="icon-btn" onclick="go('${back}')">‹</button>`:''}<h1>${title}</h1><button class="icon-btn" onclick="go('cart')">🛍</button></header>`; }
function nav(active='home') { return `<nav class="bottom-nav"><button class="nav-item ${active==='home'?'active':''}" onclick="go('catalog')"><b>⌂</b>Início</button><button class="nav-item ${active==='orders'?'active':''}" onclick="go('orders')"><b>▤</b>Pedidos</button><button class="nav-item" onclick="go('service')"><b>◌</b>Atendimento</button><button class="nav-item ${active==='account'?'active':''}" onclick="go('account')"><b>◉</b>Conta</button></nav>`; }
function summary() { return `<div class="summary"><div class="summary-row"><span>Subtotal</span><b>${money(subtotal())}</b></div><div class="summary-row"><span>Taxa de entrega</span><b>${money(fee())}</b></div><div class="summary-row summary-total"><span>Total</span><span>${money(subtotal()+fee())}</span></div></div>`; }
function productCard(item) { return `<button class="product-card" onclick="selectProduct('${item.id}')"><div class="product-art">${item.icon}</div><div class="product-info"><p class="product-name">${item.name}</p><span class="product-price">${money(item.price)}</span></div></button>`; }
function categoryName(category) { return ({cakes:'Bolos tradicionais','celebration-cakes':'Bolos comemorativos',sweets:'Doces e kits'})[category]; }
function login(admin=false) { return `<section class="auth"><img class="logo" src="../DivinoBolos_Logo.png" alt="Divino Bolos"><h1 class="brand">${admin?'Painel Divino':'Divino Bolos'}</h1><p class="tagline">${admin?'Acesso administrativo':'Bolos feitos para adoçar seu dia'}</p><label class="field">E-mail<input type="email" placeholder="voce@email.com"></label><label class="field">Senha<input type="password" placeholder="••••••••"></label>${button(admin?'Entrar no painel':'Entrar',`go('${admin?'admin-dashboard':'catalog'}')`)}<button class="text-button">Esqueci minha senha</button>${admin?'':`<div class="divider"></div><p class="hint" style="text-align:center">Ainda não tem conta?</p>${button('Criar minha conta',"go('register')",'secondary')}`}<div class="grow"></div><button class="text-button" onclick="go('${admin?'login':'admin-login'}')">${admin?'Sou cliente':'Acesso administrativo'}</button></section>`; }
function register() { return `<section class="screen">${screenHeader('Criar conta','login')}<p class="hint">Cadastre-se para acompanhar pedidos e finalizar sua compra.</p><label class="field">Nome completo<input placeholder="Maria da Silva"></label><label class="field">E-mail<input type="email" placeholder="maria@email.com"></label><label class="field">Telefone<input placeholder="(73) 99999-9999"></label><label class="field">Senha<input type="password" placeholder="Mínimo de 6 caracteres"></label>${button('Criar conta',"go('catalog')")}</section>`; }
function catalog() { const visible=state.products.filter(item=>!item.hidden&&item.available&&(state.category==='all'||item.category===state.category)); return `<section class="screen">${screenHeader('Olá, Maria',null)}<div class="hero"><span class="badge">FEITO COM CARINHO</span><h2>Sabor que vira memória.</h2><p>Escolha seu bolo favorito.</p></div><div class="search">⌕ &nbsp; Buscar no catálogo</div><div class="chips"><button class="chip ${state.category==='all'?'active':''}" onclick="filterCategory('all')">Todos</button>${['cakes','celebration-cakes','sweets'].map(category=>`<button class="chip ${state.category===category?'active':''}" onclick="filterCategory('${category}')">${categoryName(category)}</button>`).join('')}</div><h2 class="section-title">${state.category==='all'?'Mais pedidos':categoryName(state.category)}</h2><div class="products">${visible.map(productCard).join('')}</div>${nav('home')}</section>`; }
function detail() { const item=product(state.selectedProduct); return `<section class="screen">${screenHeader('Detalhes','catalog')}<div class="detail-art">${item.icon}</div><span class="badge">${categoryName(item.category)}</span><h2 class="section-title">${item.name}</h2><p class="price-large">${money(item.price)}</p><p class="description">${item.description}</p><div class="divider"></div><p class="small-title">Quantidade</p><div class="quantity"><button onclick="changeDetailQuantity(-1)">−</button><span id="detail-quantity">1</span><button onclick="changeDetailQuantity(1)">+</button></div><div class="grow"></div>${button('Adicionar ao carrinho',"addSelectedToCart()")}</section>`; }
function cart() { const items=cartItems(); return `<section class="screen">${screenHeader('Meu carrinho','catalog')}${items.length?`${items.map(item=>`<article class="cart-item"><div class="cart-art">${item.icon}</div><div class="cart-info"><p class="small-title">${item.name}</p><p class="product-price">${money(item.price)}</p><div class="inline-action"><div class="quantity"><button onclick="updateQuantity('${item.id}',-1)">−</button><span>${item.quantity}</span><button onclick="updateQuantity('${item.id}',1)">+</button></div><button class="remove" onclick="removeItem('${item.id}')">Remover</button></div></div></article>`).join('')}${summary()}${button('Continuar compra',"go('delivery')")}`:`<div class="empty"><div style="font-size:45px">🛍</div><h2>Seu carrinho está vazio</h2><p>Adicione delícias do catálogo.</p>${button('Ver catálogo',"go('catalog')")}</div>`}</section>`; }
function delivery() { return `<section class="screen">${screenHeader('Como deseja receber?','cart')}<p class="hint">Escolha uma modalidade para seu pedido.</p><button class="option-card ${state.delivery==='pickup'?'selected':''}" onclick="setDelivery('pickup')"><b class="option-icon">🏪</b><span><b>Retirar na loja</b>Rua das Flores, 120, Centro<br>Taxa: R$ 0,00</span></button><button class="option-card ${state.delivery==='delivery'?'selected':''}" onclick="setDelivery('delivery')"><b class="option-icon">🛵</b><span><b>Receber em casa</b>Informe seu endereço em Barro Preto - BA<br>Taxa simulada: R$ 8,00</span></button>${state.delivery==='delivery'?`<h2 class="section-title">Endereço de entrega</h2><label class="field">Rua e número<input id="address" placeholder="Ex.: Rua do Sol, 45"></label><label class="field">Bairro<input placeholder="Centro"></label><label class="field">Complemento <span class="hint">(opcional)</span><input placeholder="Casa, apto, referência"></label>`:`<div class="summary"><b>Endereço para retirada</b><p class="hint">Rua das Flores, 120, Centro, Barro Preto - BA</p></div>`}${button('Ir para pagamento',"continueToPayment()")}</section>`; }
function payment() { return `<section class="screen">${screenHeader('Pagamento','delivery')}<div class="summary"><b>Total do pedido</b><div class="price-large">${money(subtotal()+fee())}</div><p class="hint">Pagamento somente simulado. Nenhum dado financeiro será solicitado.</p></div><h2 class="section-title">Forma de pagamento</h2>${['Pix','Cartão','Dinheiro'].map(method=>`<label class="radio-row"><input type="radio" name="payment" ${state.payment===method?'checked':''} onchange="setPayment('${method}')"><span><b>${method}</b><br><span class="hint">Pagamento na confirmação do pedido</span></span></label>`).join('')}${button('Revisar pedido',"go('review-order')")}</section>`; }
function reviewOrder() { return `<section class="screen">${screenHeader('Revise seu pedido','payment')}<p class="hint">Confira dados antes de confirmar. Valores ficam registrados no pedido.</p>${orderData()}${button('Confirmar pedido',"go('confirmation')")}</section>`; }
function orderData() { return `<div class="order-card"><div class="order-head"><b>#DB-2025-042</b><span class="status">received</span></div><p>18 de maio de 2025 · 14:30</p><p>${cartItems().map(item=>`${item.quantity}× ${item.name}`).join('<br>')}</p><div class="divider"></div><p>Subtotal: ${money(subtotal())}</p><p>Taxa: ${money(fee())}</p><p><b>Total: ${money(subtotal()+fee())}</b></p><p><b>${state.delivery==='pickup'?'Retirada na loja':'Entrega'}</b> · ${state.delivery==='pickup'?'Rua das Flores, 120, Centro, Barro Preto - BA':'Rua do Sol, 45, Centro, Barro Preto - BA'}</p><p>Pagamento simulado: ${state.payment}</p></div>`; }
function confirmation() { return `<section class="screen success"><div class="success-mark">✓</div><h1 class="brand">Pedido recebido!</h1><p class="tagline">Estamos preparando tudo com carinho.</p><p class="order-number">Pedido #DB-2025-042</p><span class="status">received</span>${orderData()}${button('Acompanhar pedido',"go('order-detail')")}<button class="text-button" onclick="go('catalog')">Voltar ao catálogo</button></section>`; }
function orders() { return `<section class="screen">${screenHeader('Meus pedidos','catalog')}<p class="hint">Somente seus pedidos aparecem aqui.</p>${orderData()}<article class="order-card"><div class="order-head"><b>#DB-2025-031</b><span class="status">completed</span></div><p>02 de maio de 2025 · Retirada</p><p>1× Bolo de cenoura</p><p><b>R$ 42,00</b></p></article>${nav('orders')}</section>`; }
function orderDetail() { return `<section class="screen">${screenHeader('Detalhe do pedido','orders')}<div class="status-flow"><span class="status-step current">received</span><span class="status-step">preparing</span><span class="status-step">${state.delivery==='pickup'?'ready':'on_the_way'}</span><span class="status-step">completed</span></div><p class="hint" style="text-align:center">Pedido recebido. Aguarde preparação.</p>${orderData()}${button('Avaliar pedido',"go('review')",'secondary')}</section>`; }
function service() { return `<section class="screen">${screenHeader('Atendimento','catalog')}<div class="empty"><div style="font-size:57px">💬</div><h2>Precisa de ajuda?</h2><p>Fale com equipe Divino Bolos pelo WhatsApp. Atendimento sem chat interno.</p><a class="whatsapp" href="https://wa.me/5573982097690" target="_blank" rel="noopener">Abrir WhatsApp</a></div>${nav()}</section>`; }
function review() { return `<section class="screen">${screenHeader('Avaliar pedido','order-detail')}<div class="success-mark">★</div><h2 class="brand">Como foi sua experiência?</h2><p class="tagline">Sua opinião ajuda a Divino Bolos.</p><div class="stars">${[1,2,3,4,5].map(number=>`<button class="star ${number<=state.rating?'selected':''}" onclick="setRating(${number})">★</button>`).join('')}</div><p class="hint" style="text-align:center">Nota ${state.rating||'—'} de 5</p><label class="field">Comentário <span class="hint">(opcional)</span><textarea placeholder="Conte como foi seu pedido..."></textarea></label>${button('Enviar avaliação',"go('orders')")}</section>`; }
function account() { return `<section class="screen">${screenHeader('Minha conta','catalog')}<div class="admin-hero"><b>Maria da Silva</b><p>maria@email.com</p></div><div class="menu-list"><button onclick="go('orders')">Meus pedidos <span>›</span></button><button onclick="go('service')">Atendimento <span>›</span></button><button onclick="go('login')">Sair da conta <span>›</span></button></div>${nav('account')}</section>`; }
function adminDashboard() { return `<section class="screen">${screenHeader('Painel admin',null)}<div class="admin-hero"><b>Olá, Administrador</b><p>Gerencie pedidos e catálogo.</p></div><div class="stat-grid"><div class="stat"><b>8</b><span>Pedidos ativos</span></div><div class="stat"><b>12</b><span>Produtos ativos</span></div></div><div class="menu-list"><button onclick="go('admin-orders')">📦 Pedidos <span>›</span></button><button onclick="go('admin-products')">🍰 Produtos <span>›</span></button><button onclick="go('admin-login')">↪ Sair da conta <span>›</span></button></div></section>`; }
function adminOrders() { return `<section class="screen">${screenHeader('Pedidos','admin-dashboard')}<button class="chip active">Todos</button><article class="order-card" onclick="openAdminOrder('delivery')"><div class="order-head"><b>#DB-2025-042</b><span class="status">received</span></div><p>Maria da Silva · Entrega</p><p>R$ 83,00 · 18 maio, 14:30</p></article><article class="order-card" onclick="openAdminOrder('pickup')"><div class="order-head"><b>#DB-2025-041</b><span class="status">preparing</span></div><p>João Santos · Retirada</p><p>R$ 110,00 · 18 maio, 13:10</p></article></section>`; }
function adminOrderDetail() { const pickup=state.adminMode==='pickup'; const statuses=pickup?['received','preparing','ready','completed']:['received','preparing','on_the_way','completed']; const index=statuses.indexOf(state.adminStatus); const number=pickup?'#DB-2025-041':'#DB-2025-042'; return `<section class="screen">${screenHeader(`Pedido ${number}`,'admin-orders')}<p class="hint">Cliente: ${pickup?'João Santos · Retirada':'Maria da Silva · Entrega'}</p><div class="status-flow">${statuses.map((status,i)=>`<span class="status-step ${i<index?'done':''} ${i===index?'current':''}">${status}</span>`).join('')}</div>${pickup?`<div class="summary"><b>Retirada na loja</b><p class="hint">Rua das Flores, 120, Centro, Barro Preto - BA</p></div>`:orderData()}<h2 class="section-title">Atualizar status</h2><p class="hint">Fluxo de ${pickup?'retirada':'entrega'} sem salto: ${statuses.join(' → ')}.</p>${index<statuses.length-1?button(`Avançar para ${statuses[index+1]}`,`advanceStatus()`):`<div class="summary"><b>Pedido concluído</b></div>`}</section>`; }
function adminProducts() { return `<section class="screen">${screenHeader('Produtos','admin-dashboard')}${button('+ Cadastrar produto',"go('admin-product-form')",'secondary')}<div>${state.products.map(item=>`<article class="product-admin"><div class="cart-art">${item.icon}</div><div class="product-admin-info"><b>${item.name}</b><p>${money(item.price)} · ${item.hidden?'Oculto':item.available?'Disponível':'Indisponível'}</p><button class="text-button" onclick="editProduct('${item.id}')">Editar</button></div><button class="switch ${item.available?'on':''}" onclick="toggleAvailable('${item.id}')"><span></span></button></article>`).join('')}</div></section>`; }
function productForm() { const item=state.editing?product(state.editing):null; return `<section class="screen">${screenHeader(item?'Editar produto':'Cadastrar produto','admin-products')}<label class="field">Nome do produto<input value="${item?item.name:''}" placeholder="Ex.: Bolo de chocolate"></label><label class="field">Categoria<select><option>Bolos tradicionais</option><option>Bolos comemorativos</option><option>Doces e kits</option></select></label><label class="field">Descrição<textarea>${item?item.description:''}</textarea></label><label class="field">Preço<input value="${item?money(item.price):''}" placeholder="R$ 0,00"></label><label class="field">Imagem demonstrativa<input placeholder="Selecionar imagem local"></label><label class="radio-row"><input type="checkbox" checked> Produto disponível</label>${button(item?'Salvar alterações':'Cadastrar produto',"go('admin-products')")}${item?button(item.hidden?'Mostrar produto no catálogo':'Ocultar produto do catálogo',"toggleHidden('${item.id}')",'danger'):''}</section>`; }
const screens={login:()=>login(),register, 'admin-login':()=>login(true),catalog,detail,cart,delivery,payment,'review-order':reviewOrder,confirmation,orders,'order-detail':orderDetail,service,review,account,'admin-dashboard':adminDashboard,'admin-orders':adminOrders,'admin-order-detail':adminOrderDetail,'admin-products':adminProducts,'admin-product-form':productForm};
function render() { const screen=location.hash.slice(1)||'login'; app.innerHTML=(screens[screen]||screens.login)(); app.scrollTop=0; }
function selectProduct(id){state.selectedProduct=id;go('detail')} function filterCategory(category){state.category=category;render()} function openAdminOrder(mode){state.adminMode=mode;state.adminStatus=mode==='pickup'?'preparing':'received';go('admin-order-detail')} function setDelivery(value){state.delivery=value;render()} function setPayment(value){state.payment=value} function setRating(value){state.rating=value;render()} function changeDetailQuantity(delta){const element=document.querySelector('#detail-quantity'); element.textContent=Math.max(1,+element.textContent+delta)} function addSelectedToCart(){const quantity=+document.querySelector('#detail-quantity').textContent; const item=state.cart.find(entry=>entry.id===state.selectedProduct); item?item.quantity+=quantity:state.cart.push({id:state.selectedProduct,quantity});go('cart')} function updateQuantity(id,delta){const item=state.cart.find(entry=>entry.id===id);item.quantity+=delta;if(item.quantity<1)state.cart=state.cart.filter(entry=>entry.id!==id);render()} function removeItem(id){state.cart=state.cart.filter(item=>item.id!==id);render()} function continueToPayment(){if(state.delivery==='delivery'&&!document.querySelector('#address').value.trim()){document.querySelector('#address').focus();return}go('payment')} function advanceStatus(){const statuses=state.adminMode==='pickup'?['received','preparing','ready','completed']:['received','preparing','on_the_way','completed'];state.adminStatus=statuses[statuses.indexOf(state.adminStatus)+1];render()} function toggleAvailable(id){product(id).available=!product(id).available;render()} function editProduct(id){state.editing=id;go('admin-product-form')} function toggleHidden(id){product(id).hidden=!product(id).hidden;go('admin-products')}
window.go=go;window.selectProduct=selectProduct;window.filterCategory=filterCategory;window.openAdminOrder=openAdminOrder;window.setDelivery=setDelivery;window.setPayment=setPayment;window.setRating=setRating;window.changeDetailQuantity=changeDetailQuantity;window.addSelectedToCart=addSelectedToCart;window.updateQuantity=updateQuantity;window.removeItem=removeItem;window.continueToPayment=continueToPayment;window.advanceStatus=advanceStatus;window.toggleAvailable=toggleAvailable;window.editProduct=editProduct;window.toggleHidden=toggleHidden;window.addEventListener('hashchange',render);render();
